name: KalpApp
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^0.13.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/opening_screen.png
    - assets/sign_in_img.png
    - assets/location.png
    - assets/current_location.png
    - assets/continue.png
    - assets/school.png
    - assets/welcome.png
    - assets/facebook_logo.png
    - assets/google_logo.png
    - assets/signin.png
    - assets/icon_edit_profile.png
    - assets/school_bag.png
    - assets/uniform.png
    - assets/shoes.png
    - assets/search_product.png
    - assets/icon_alert.png
    - assets/icon_exit.png
    - assets/icon_history.png
    - assets/icon_location.png
    - assets/icon_wishlist.png
    - assets/icon_order.png
    - assets/icon_payment.png
    - assets/img.png
    - assets/menu.png
    - assets/ico_menu_light.png
    - assets/primary_button_small.png
    - assets/radio_button.png
    - assets/icon_saved_cards.png
    - assets/icons_paypal.png
    - assets/icon_master_card.png
    - assets/order_placed.png
    - assets/left_arrow.png
    - assets/kalap_logos.png
